# Generated by Django 3.2.7 on 2021-09-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.PositiveIntegerField(default=0, editable=False)),
                ('request_id', models.CharField(editable=False, max_length=100)),
                ('caliber', models.DecimalField(db_index=True, decimal_places=3, max_digits=5)),
                ('caliber_type', models.CharField(choices=[('MNB', 'MiniatureBore'), ('SB', 'SmallBore'), ('MB', 'MediumBore'), ('LB', 'LargeBore')], max_length=3)),
                ('damage_modifier', models.FloatField(default=1.0)),
                ('skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ammunition', to='skins.skin')),
            ],
        ),
    ]
