# Generated by Django 3.2.7 on 2021-09-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.PositiveIntegerField(default=0, editable=False)),
                ('request_id', models.CharField(default='', editable=False, max_length=100)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
