# Generated by Django 3.2.7 on 2021-09-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.PositiveIntegerField(default=0, editable=False)),
                ('request_id', models.CharField(default='', editable=False, max_length=100)),
                ('type', models.CharField(choices=[('S', 'Scope'), ('DM', 'DoubleMagazine'), ('GL', 'GrenadeLauncher'), ('LS', 'LaserScope')], max_length=2)),
                ('skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skins.skin')),
            ],
        ),
    ]
