# Generated by Django 3.2.7 on 2021-09-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('throwables', '0001_initial'),
        ('firearms', '0001_initial'),
        ('users', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.PositiveIntegerField(default=0, editable=False)),
                ('request_id', models.CharField(default='', editable=False, max_length=100)),
                ('score', models.FloatField()),
                ('team_id', models.IntegerField(db_index=True)),
                ('inventory_size', models.IntegerField(default=10)),
                ('inventory_weight', models.FloatField()),
                ('firearms', models.ManyToManyField(blank=True, null=True, to='firearms.Firearm')),
                ('supplies', models.ManyToManyField(blank=True, null=True, to='supplies.Supply')),
                ('throwables', models.ManyToManyField(blank=True, null=True, to='throwables.Throwable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
        ),
    ]
